"""empty message

Revision ID: 1515ecd33ef9
Revises: 62d17daa4dfe
Create Date: 2022-11-04 05:09:04.055905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1515ecd33ef9'
down_revision = '62d17daa4dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predeterminedroutines_table', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predeterminedroutines_table', 'trackerpred_table', ['track_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predeterminedroutines_table', type_='foreignkey')
    op.drop_column('predeterminedroutines_table', 'track_id')
    # ### end Alembic commands ###
