"""empty message

Revision ID: 348a8fca123a
Revises: 72684f6a46fe
Create Date: 2022-11-04 03:50:23.823578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348a8fca123a'
down_revision = '72684f6a46fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predeterminedroutines_table', sa.Column('description', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'predeterminedroutines_table', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predeterminedroutines_table', type_='unique')
    op.drop_column('predeterminedroutines_table', 'description')
    # ### end Alembic commands ###
