"""empty message

Revision ID: 48bf739384d4
Revises: 8cabc57ad5fc
Create Date: 2022-11-04 04:01:04.549859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bf739384d4'
down_revision = '8cabc57ad5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_table', sa.Column('muscle_group', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'group_table', ['muscle_group'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_table', type_='unique')
    op.drop_column('group_table', 'muscle_group')
    # ### end Alembic commands ###
