"""empty message

Revision ID: 62d17daa4dfe
Revises: 48bf739384d4
Create Date: 2022-11-04 05:04:26.651716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d17daa4dfe'
down_revision = '48bf739384d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackerpred_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('burnt_cals', sa.Float(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('daily_steps', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.add_column('exercises_table', sa.Column('burnt_calories', sa.Float(), nullable=False))
    op.add_column('user_table', sa.Column('tracker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_table', 'trackerpred_table', ['tracker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'tracker_id')
    op.drop_column('exercises_table', 'burnt_calories')
    op.drop_table('trackerpred_table')
    # ### end Alembic commands ###
