"""empty message

Revision ID: 64afcea64462
Revises: c1d95cf2b31b
Create Date: 2022-11-04 05:25:46.280431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64afcea64462'
down_revision = 'c1d95cf2b31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackerfree_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('burnt_cals', sa.Float(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('daily_steps', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.add_column('freeroutine_table', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'freeroutine_table', 'trackerfree_table', ['track_id'], ['id'])
    op.add_column('user_table', sa.Column('freetracker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_table', 'trackerfree_table', ['freetracker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'freetracker_id')
    op.drop_constraint(None, 'freeroutine_table', type_='foreignkey')
    op.drop_column('freeroutine_table', 'track_id')
    op.drop_table('trackerfree_table')
    # ### end Alembic commands ###
