"""empty message

Revision ID: a610f6c766e3
Revises: 5e2428281bc9
Create Date: 2022-11-04 03:19:27.188761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a610f6c766e3'
down_revision = '5e2428281bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muscle_group')
    )
    op.add_column('muscles_table', sa.Column('groupid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'muscles_table', 'group_table', ['groupid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'muscles_table', type_='foreignkey')
    op.drop_column('muscles_table', 'groupid')
    op.drop_table('group_table')
    # ### end Alembic commands ###
