"""empty message

Revision ID: b414bc70b11f
Revises: 64afcea64462
Create Date: 2022-11-04 05:34:38.723533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414bc70b11f'
down_revision = '64afcea64462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackerpred_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trackerpred_table', 'user_table', ['user_id'], ['id'])
    op.drop_constraint('user_table_tracker_id_fkey', 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'tracker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('tracker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_table_tracker_id_fkey', 'user_table', 'trackerpred_table', ['tracker_id'], ['id'])
    op.drop_constraint(None, 'trackerpred_table', type_='foreignkey')
    op.drop_column('trackerpred_table', 'user_id')
    # ### end Alembic commands ###
