"""empty message

Revision ID: c2087f04fc59
Revises: db2191ba3df7
Create Date: 2022-11-15 02:28:45.018190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2087f04fc59'
down_revision = 'db2191ba3df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises_table', schema=None) as batch_op:
        batch_op.drop_column('burnt_calories')

    with op.batch_alter_table('freeroutine_table', schema=None) as batch_op:
        batch_op.drop_column('burnt_calories')

    with op.batch_alter_table('predeterminedroutines_table', schema=None) as batch_op:
        batch_op.drop_column('burnt_calories')

    with op.batch_alter_table('trackerfree_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('avg_bpm', sa.Float(), nullable=False))
        batch_op.drop_column('daily_steps')

    with op.batch_alter_table('trackerpred_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('avg_bpm', sa.Float(), nullable=False))
        batch_op.drop_column('daily_steps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackerpred_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_steps', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('avg_bpm')
        batch_op.drop_column('duration')

    with op.batch_alter_table('trackerfree_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_steps', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('avg_bpm')
        batch_op.drop_column('duration')

    with op.batch_alter_table('predeterminedroutines_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burnt_calories', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('freeroutine_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burnt_calories', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('exercises_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burnt_calories', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
