"""empty message

Revision ID: db2191ba3df7
Revises: e4873dd106eb
Create Date: 2022-11-15 02:17:03.915610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db2191ba3df7'
down_revision = 'e4873dd106eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_table')
    with op.batch_alter_table('exercises_table', schema=None) as batch_op:
        batch_op.drop_constraint('exercises_table_name_key', type_='unique')

    with op.batch_alter_table('freeroutine_table', schema=None) as batch_op:
        batch_op.drop_constraint('freeroutine_table_description_key', type_='unique')
        batch_op.drop_constraint('freeroutine_table_routine_name_key', type_='unique')

    with op.batch_alter_table('predeterminedroutines_table', schema=None) as batch_op:
        batch_op.drop_constraint('predeterminedroutines_table_description_key', type_='unique')
        batch_op.drop_constraint('predeterminedroutines_table_routine_name_key', type_='unique')

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_birthday', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('muscle_mass', sa.Float(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_birthday'])
        batch_op.create_unique_constraint(None, ['height'])
        batch_op.create_unique_constraint(None, ['weight'])
        batch_op.create_unique_constraint(None, ['bmi'])
        batch_op.create_unique_constraint(None, ['muscle_mass'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('muscle_mass')
        batch_op.drop_column('bmi')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('user_birthday')

    with op.batch_alter_table('predeterminedroutines_table', schema=None) as batch_op:
        batch_op.create_unique_constraint('predeterminedroutines_table_routine_name_key', ['routine_name'])
        batch_op.create_unique_constraint('predeterminedroutines_table_description_key', ['description'])

    with op.batch_alter_table('freeroutine_table', schema=None) as batch_op:
        batch_op.create_unique_constraint('freeroutine_table_routine_name_key', ['routine_name'])
        batch_op.create_unique_constraint('freeroutine_table_description_key', ['description'])

    with op.batch_alter_table('exercises_table', schema=None) as batch_op:
        batch_op.create_unique_constraint('exercises_table_name_key', ['name'])

    op.create_table('profile_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bmi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fat_percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name='profile_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_table_pkey'),
    sa.UniqueConstraint('age', name='profile_table_age_key'),
    sa.UniqueConstraint('bmi', name='profile_table_bmi_key'),
    sa.UniqueConstraint('fat_percentage', name='profile_table_fat_percentage_key'),
    sa.UniqueConstraint('height', name='profile_table_height_key'),
    sa.UniqueConstraint('weight', name='profile_table_weight_key')
    )
    # ### end Alembic commands ###
