"""empty message

Revision ID: e4873dd106eb
Revises: 17121af6f25a
Create Date: 2022-11-09 23:54:59.996623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4873dd106eb'
down_revision = '17121af6f25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises_table', 'description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises_table', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
